version: 2
 
models:
  - name: example_model
    description: "Ceci est une nouvelle description pour tester la mise à jour automatique"
    columns:
      - name: id
        description: "Identifiant unique."
      - name: date_sample
        description: "Date d'exemple."
      - name: montant
        description: "Montant de démonstration."